//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotMapProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSpot
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<bool> @public { get; set; }
        public Nullable<bool> added { get; set; }
        public string author { get; set; }
    }
}
